# Generated by Django 5.2 on 2025-04-18 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumpack',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='albumpack',
            name='description',
        ),
        migrations.RemoveField(
            model_name='albumpack',
            name='likes',
        ),
    ]
