# Generated by Django 5.2 on 2025-04-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('packs', '0002_remove_albumpack_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumpack',
            name='albums',
            field=models.ManyToManyField(related_name='album_packs', to='albums.album'),
        ),
    ]
