# Generated by Django 5.2 on 2025-04-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0003_albumpack_albums'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumpack',
            name='albums',
        ),
        migrations.AddField(
            model_name='albumpack',
            name='albums',
            field=models.JSONField(default=list),
        ),
    ]
