# Generated by Django 5.2 on 2025-04-23 18:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_remove_albumpack_albums_albumpack_albums'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumpack',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='album_packs', to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumpack',
            name='description',
            field=models.TextField(default='New Pack'),
            preserve_default=False,
        ),
    ]
