# Generated by Django 5.2 on 2025-04-23 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0004_remove_albumpack_albums_albumpack_albums'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='albumpack',
            name='comments',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='albumpack',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_packs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='albumpack',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
