# Generated by Django 5.2 on 2025-06-13 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_albumpack_creator_albumpack_description'),
        ('users', '0002_remove_userprofile_profile_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albumpack',
            name='slug',
        ),
        migrations.AddField(
            model_name='albumpack',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='album_packs', to='users.userprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumpack',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
