# Generated by Django 5.2 on 2025-04-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packs', '0005_albumpack_comments_albumpack_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumpack',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
