# Generated by Django 5.2 on 2025-04-22 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_album_genre_remove_album_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='artist',
            new_name='artists',
        ),
    ]
